version: '3.8'

services:
  test-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicanted
      replicas: 1